# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_auto_20170310_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgoal',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subgoal',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
